"""
Django settings for kwt_ideas1 project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "home",

    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    "wagtail.rich_text",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    'django_otp',
    'django_otp.plugins.otp_totp',  # Для приложений аутентификации (Google Authenticator)
    'django_otp.plugins.otp_email',  # Для email кодов
    'django_otp.plugins.otp_static',  # Для резервных кодов
    
]
SITE_ID = 1
MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    'django_otp.middleware.OTPMiddleware',
    'home.middleware.TwoFactorAuthMiddleware',
    'home.middleware.RememberDeviceMiddleware',
    'home.middleware.PasswordChangeMiddleware',
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    'allauth.account.middleware.AccountMiddleware',
    
]
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
ROOT_URLCONF = "kwt_ideas1.urls"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'home.notifications.unread_messages',
            ],
            'libraries': {  # Если хотите явно указать (не обязательно)
                'app_filters': 'home.templatetags.app_filters',
            },
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

]




SITE_ID = 1
# settings.py
EMAIL_CHANGE_COOLDOWN = 60  # seconds
USERNAME_CHANGE_COOLDOWN = 60  # seco
PASSWORD_CHANGE_COOLDOWN = 60  # seconds
# Настройки для OAuth 2.0
GOOGLE_OAUTH2_CLIENT_ID = '563909432254-h4bdmsjb5q7ra6clha5pb46ovnqp4mtp.apps.googleusercontent.com'
GOOGLE_OAUTH2_CLIENT_SECRET = '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'
GOOGLE_OAUTH2_REDIRECT_URI = 'http://127.0.0.1:8000/oauth2callback/'
SOCIAL_AUTH_GOOGLE_CLIENT_ID = '563909432254-h4bdmsjb5q7ra6clha5pb46ovnqp4mtp.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_SECRET = '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'
SOCIAL_AUTH_GOOGLE_SCOPE = ['email']  # Список разрешений (например, только email)
SOCIAL_AUTH_GOOGLE_EXTRA_DATA = ['first_name', 'last_name']  # Дополнительные данные

# allauth

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300  # 5 минут
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_LOGIN_METHODS = ['email','username']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True  # Используйте HMAC вместо подписи
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Автовход после подтверждения
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_TEMPLATE = "account/email_confirmation"
ACCOUNT_EMAIL_CONFIRMATION_SUBJECT = None  # Используем txt файл для темы

LOGIN_REDIRECT_URL = '/'
# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_USE_TLS = True

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_PORT = 465
EMAIL_HOST_USER = 'kwt.ideas@gmail.com'  # Ваш email
EMAIL_HOST_PASSWORD = 'vypisfvaopjhgkcu'  # Пароль для приложения
#EMAIL_HOST_PASSWORD = 'kwt277382'  # Пароль для приложения
DEFAULT_FROM_EMAIL = 'kwt.ideas@gmail.com'
EMAIL_TIMEOUT = 10
ACCOUNT_FORMS = {
    'signup': 'home.forms.RegisterForm',
}
SESSION_COOKIE_NAME = 'kwt_session'
CSRF_COOKIE_SECURE = False  # Для разработки без HTTPS
SESSION_COOKIE_SECURE = False  # Для разработки
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Сессия сохраняется после закрытия браузера
ACCOUNT_SESSION_REMEMBER = True  # Для allauth
SESSION_COOKIE_NAME = 'kwt_secure_session'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 дней
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True

SESSION_COOKIE_SAMESITE = 'Lax'
# Настройки для django-otp
OTP_LOGIN_URL = '/account/2fa/'
OTP_EMAIL_SUBJECT = 'Ваш код подтверждения'
OTP_EMAIL_SENDER = 'kwt.ideas@gmail.com'  # Email отправителя кодов
OTP_EMAIL_SUBJECT = 'Ваш код подтверждения'  # Тема письма
OTP_EMAIL_SENDER = None  # Отключаем встроенную отправку писем
OTP_EMAIL_NO_DELIVERY = True  # Отключаем автоматическую отправку писем
OTP_LOGIN_URL = 'two-factor-authenticate'
LOGIN_URL = 'account_login'
ACCOUNT_LOGIN_VIEW = 'home.views.CustomLoginView'  # Добавь это
LOGIN_REDIRECT_URL = 'dashboard'
OTP_DEVICE_VALIDITY = 60 * 60 * 24 * 30  # 30 дней

EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")
if not os.path.exists(EMAIL_FILE_PATH):
    os.makedirs(EMAIL_FILE_PATH)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "custom_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "auth_debug.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "auth": {
            "handlers": ["custom_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
WSGI_APPLICATION = "kwt_ideas1.wsgi.application"
ASGI_APPLICATION = 'kwt_ideas1.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        'OPTIONS': {
            'isolation_level': None,
            'timeout': 30,
        },
        'TEST': {
            'CHARSET': 'UTF8',
            'COLLATION': 'utf8_general_ci',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
MEDIA_URL = '/protected/media/'  # Изменили с /media/
X_FRAME_OPTIONS = 'DENY'  # Защита от clickjacking
# Default storage settings, with the staticfiles storage updated.
# See https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # ManifestStaticFilesStorage is recommended in production, to prevent
    # outdated JavaScript / CSS assets being served from cache
    # (e.g. after a Wagtail upgrade).
    # See https://docs.djangoproject.com/en/5.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "kwt_ideas1"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"
ALLOWED_HOSTS = ['kwt_ideas1.onrender.com', '0.0.0.0']
# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']
# После входа перенаправлять пользователя в личный кабинет
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = 'home'
ACCOUNT_LOGOUT_ON_GET = True