# Generated by Django 5.1.6 on 2025-03-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_application_educational_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('under_review', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='draft', max_length=20),
        ),
    ]
