# Generated by Django 5.1.6 on 2025-03-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('under_review', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='submitted', max_length=20),
        ),
    ]
