# Generated by Django 5.1.6 on 2025-04-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
    ]
