# Generated by Django 5.1.6 on 2025-04-20 04:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_application_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Идентификационный номер'),
        ),
        migrations.AddField(
            model_name='application',
            name='comparative_advantages',
            field=models.TextField(blank=True, null=True, verbose_name='Сравнительные преимущества'),
        ),
        migrations.AddField(
            model_name='application',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='application',
            name='development_basis',
            field=models.TextField(blank=True, null=True, verbose_name='Основание для разработки'),
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата внедрения'),
        ),
        migrations.AddField(
            model_name='application',
            name='pni_project',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Проект ПНИ'),
        ),
        migrations.AddField(
            model_name='application',
            name='replication_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Оценка возможности тиражирования'),
        ),
        migrations.AddField(
            model_name='application',
            name='research_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Научная группа'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание и характеристики разработки'),
        ),
    ]
