# Generated by Django 5.1.6 on 2025-04-20 04:21

from django.db import migrations
import uuid

def fill_uuids(apps, schema_editor):
    Application = apps.get_model('home', 'Application')
    for app in Application.objects.all():
        app.application_id = uuid.uuid4()
        app.save()

class Migration(migrations.Migration):
    dependencies = [
        ('home', '0028_application_application_id_and_more'),  # Укажите имя предыдущей миграции
    ]

    operations = [
        migrations.RunPython(fill_uuids),
    ]