# Generated by Django 5.1.6 on 2025-04-20 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_fill_application_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификационный номер'),
        ),
    ]
