# Generated by Django 5.1.6 on 2025-04-20 04:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_application_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Идентификационный номер'),
        ),
    ]
