# Generated by Django 5.1.6 on 2025-02-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_application_department_application_expected_effect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='attached_files',
        ),
        migrations.RemoveField(
            model_name='application',
            name='department',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expected_effect',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='application',
            name='implementation_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='process_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='authors',
            field=models.TextField(blank=True, null=True, verbose_name='Авторы инновации'),
        ),
        migrations.AddField(
            model_name='application',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='application',
            name='innovation_type',
            field=models.CharField(choices=[('educational', 'Образовательная'), ('scientific', 'Научно-техническая'), ('process', 'Процессная'), ('proposal', 'Инновационное предложение')], max_length=50, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resource_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на ресурс'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название инновации'),
        ),
        migrations.AddField(
            model_name='application',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='applications', to='home.attachment'),
        ),
    ]
