# Generated by Django 5.1.6 on 2025-02-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_application_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='educational_files',
            field=models.FileField(blank=True, null=True, upload_to='educational_files/', verbose_name='Материалы ЭУМК'),
        ),
        migrations.AddField(
            model_name='application',
            name='process_files',
            field=models.FileField(blank=True, null=True, upload_to='process_files/', verbose_name='Заключение о внедрении'),
        ),
        migrations.AddField(
            model_name='application',
            name='proposal_files',
            field=models.FileField(blank=True, null=True, upload_to='proposal_files/', verbose_name='Дополнительные документы'),
        ),
        migrations.AddField(
            model_name='application',
            name='scientific_files',
            field=models.FileField(blank=True, null=True, upload_to='scientific_files/', verbose_name='Акты и документы'),
        ),
    ]
