# Generated by Django 5.1.6 on 2025-02-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_application_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attached_files',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='application',
            name='innovation_type',
            field=models.CharField(choices=[('educational', 'Образовательная'), ('scientific', 'Научно-техническая'), ('process', 'Процессная')], default='educational', max_length=50),
        ),
    ]
