# Generated by Django 5.1.6 on 2025-04-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_application_patents_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comparison_advantages',
            field=models.TextField(blank=True, null=True, verbose_name='Сравнительные преимущества'),
        ),
        
        migrations.AddField(
            model_name='application',
            name='development_basis',
            field=models.TextField(blank=True, null=True, verbose_name='Основание для разработки инновации'),
        ),
        migrations.AddField(
            model_name='application',
            name='development_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание и характеристики разработки'),
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата внедрения инновации'),
        ),
        migrations.AddField(
            model_name='application',
            name='pni_project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект ПНИ'),
        ),
        migrations.AddField(
            model_name='application',
            name='replication_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Оценка возможности тиражирования'),
        ),
        migrations.AddField(
            model_name='application',
            name='scientific_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Научная группа'),
        ),
    ]
