# Generated by Django 5.1.6 on 2025-04-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_application_comparison_advantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='application',
            name='authors',
            field=models.TextField(blank=True, null=True, verbose_name='Авторы'),
        ),
    ]
