# Generated by Django 5.1.6 on 2025-02-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_application_department_application_expected_effects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='application',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='application',
            name='implementation_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='implementation_results',
        ),
        migrations.RemoveField(
            model_name='application',
            name='innovation_content',
        ),
        migrations.RemoveField(
            model_name='application',
            name='negative_effects',
        ),
        migrations.RemoveField(
            model_name='application',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='project_pni',
        ),
        migrations.RemoveField(
            model_name='application',
            name='relevance',
        ),
        migrations.RemoveField(
            model_name='application',
            name='required_resources',
        ),
        migrations.RemoveField(
            model_name='application',
            name='scalability',
        ),
        migrations.RemoveField(
            model_name='application',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='application',
            name='tiражирование',
        ),
        migrations.AddField(
            model_name='application',
            name='process_innovation_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип инновации'),
        ),
        migrations.AddField(
            model_name='application',
            name='usage_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инновация разработана для'),
        ),
        migrations.AlterField(
            model_name='application',
            name='implementation_steps',
            field=models.TextField(blank=True, null=True, verbose_name='Шаги реализации'),
        ),
        migrations.AlterField(
            model_name='application',
            name='patents_links',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылки на патенты и статьи'),
        ),
        migrations.AlterField(
            model_name='application',
            name='readiness_level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уровень готовности'),
        ),
        migrations.AlterField(
            model_name='application',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Предлагаемое решение'),
        ),
    ]
