# Generated by Django 5.1.6 on 2025-03-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_application_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_questions',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные вопросы к автору'),
        ),
        migrations.AddField(
            model_name='application',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Обоснование оценки'),
        ),
        migrations.AddField(
            model_name='application',
            name='comparison_with_analogues',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сравнение с аналогами'),
        ),
        migrations.AddField(
            model_name='application',
            name='cost_effectiveness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отношение полезного эффекта к затратам'),
        ),
        migrations.AddField(
            model_name='application',
            name='decision',
            field=models.CharField(blank=True, choices=[('approved', 'Принять'), ('rejected', 'Отклонить')], max_length=20, null=True, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='application',
            name='effect_on_indicators',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка эффекта на показатели ПКР'),
        ),
        migrations.AddField(
            model_name='application',
            name='financial_effect',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка финансового эффекта'),
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_scale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Масштаб фактического внедрения'),
        ),
        migrations.AddField(
            model_name='application',
            name='novelty_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень новизны'),
        ),
        migrations.AddField(
            model_name='application',
            name='relevance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Актуальность для СФ МЭИ'),
        ),
        migrations.AddField(
            model_name='application',
            name='scalability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Масштабы возможного внедрения'),
        ),
        migrations.AddField(
            model_name='application',
            name='solution_quality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень проработки описания решения'),
        ),
        migrations.AddField(
            model_name='application',
            name='total_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговая оценка'),
        ),
    ]
