# Generated by Django 5.1.6 on 2025-03-28 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чатов'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_type',
            field=models.CharField(choices=[('author_expert', 'Чат автора с экспертом'), ('author_responsible', 'Чат автора с ответственным'), ('expert_responsible', 'Чат эксперта с ответственным')], default='author_expert', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='home.application'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
