# Generated by Django 5.1.6 on 2025-02-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_attachment_remove_application_attached_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кафедра/лаборатория'),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Ожидаемые эффекты'),
        ),
        migrations.AddField(
            model_name='application',
            name='frequency',
            field=models.TextField(blank=True, null=True, verbose_name='Частота возникновения проблемы'),
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата внедрения'),
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_results',
            field=models.TextField(blank=True, null=True, verbose_name='Результаты внедрения'),
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_steps',
            field=models.TextField(blank=True, null=True, verbose_name='Описание внедрения'),
        ),
        migrations.AddField(
            model_name='application',
            name='innovation_content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание инновации'),
        ),
        migrations.AddField(
            model_name='application',
            name='negative_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Негативные последствия'),
        ),
        migrations.AddField(
            model_name='application',
            name='patents_links',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылки на патенты, статьи'),
        ),
        migrations.AddField(
            model_name='application',
            name='problem_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='application',
            name='program_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Программа обучения'),
        ),
        migrations.AddField(
            model_name='application',
            name='project_pni',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект ПНИ'),
        ),
        migrations.AddField(
            model_name='application',
            name='readiness_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень готовности'),
        ),
        migrations.AddField(
            model_name='application',
            name='relevance',
            field=models.TextField(blank=True, null=True, verbose_name='Актуальность'),
        ),
        migrations.AddField(
            model_name='application',
            name='required_resources',
            field=models.TextField(blank=True, null=True, verbose_name='Необходимые ресурсы'),
        ),
        migrations.AddField(
            model_name='application',
            name='scalability',
            field=models.TextField(blank=True, null=True, verbose_name='Возможность тиражирования'),
        ),
        migrations.AddField(
            model_name='application',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Описание решения'),
        ),
        migrations.AddField(
            model_name='application',
            name='target_audience',
            field=models.TextField(blank=True, null=True, verbose_name='Целевая аудитория'),
        ),
        migrations.AddField(
            model_name='application',
            name='tiражирование',
            field=models.BooleanField(default=False, verbose_name='Тиражирование'),
        ),
    ]
