# Generated by Django 5.1.6 on 2025-03-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_application_id_alter_attachment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='scientific_product_type',
            field=models.CharField(blank=True, choices=[('product_1', 'Продукт 1: инновации в результатах ОКР'), ('product_2', 'Продукт 2: инновация в оказании технологических услуг'), ('product_3', 'Продукт 3: инновация в оказании инжиниринговых услуг')], max_length=255, null=True, verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='implementation_steps',
            field=models.TextField(blank=True, null=True, verbose_name='Описание процесса внедрения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='process_innovation_type',
            field=models.CharField(blank=True, choices=[('организационная', 'Организационная инновация'), ('технологическая', 'Технологическая инновация'), ('управленческая', 'Управленческая инновация'), ('другой', 'Другой тип инновации')], max_length=255, null=True, verbose_name='Тип инновации'),
        ),
        migrations.AlterField(
            model_name='application',
            name='product_type',
            field=models.CharField(blank=True, choices=[('МООК', 'Массовый открытый онлайн-курс (МООК)'), ('ЭУМК', 'Электронный учебно-методический комплекс (ЭУМК)'), ('ЭУМК_иностранный', 'ЭУМК на иностранном языке'), ('СПОК', 'Электронный персонифицированный онлайн-курс (СПОК)'), ('ЭОР', 'Электронный образовательный ресурс')], max_length=255, null=True, verbose_name='Тип продукта'),
        ),
    ]
