# Generated by Django 5.1.6 on 2025-03-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_application_scientific_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='educational_files',
        ),
        migrations.RemoveField(
            model_name='application',
            name='proposal_files',
        ),
        migrations.RemoveField(
            model_name='application',
            name='scientific_files',
        ),
        migrations.AddField(
            model_name='application',
            name='educational_files',
            field=models.ManyToManyField(blank=True, to='home.attachment', verbose_name='Материалы ЭУМК'),
        ),
        migrations.AddField(
            model_name='application',
            name='proposal_files',
            field=models.ManyToManyField(blank=True, related_name='proposal_attachments', to='home.attachment', verbose_name='Дополнительный документы'),
        ),
        migrations.AddField(
            model_name='application',
            name='scientific_files',
            field=models.ManyToManyField(blank=True, related_name='scientific_attachments', to='home.attachment', verbose_name='Научные материалы'),
        ),
    ]
